# 官方文档
# http://hub.docker.com/cnk3x/xunlei
# https://github.com/cnk3x/xunlei

---
version: "3"
# 最后编辑时间：2024-06-13
services:
  xunlei:
    image: cnk3x/xunlei:latest
    # 镜像地址
    container_name: xunlei
    # 容器名字
    hostname: xunlei
    # 主机名
    privileged: true
    # 特权，赋予容器与主机几乎一致的权限，必须开启
    volumes:
      - /vol1/1000/docker/xunlei:/xunlei/data
      # 配置文件目录
      - /vol1/1000/xunlei:/xunlei/downloads
      # 下载目录
      # 可以自定义，可以写多个
    environment:
      - XL_DASHBOARD_PORT=2345
      # 自定义迅雷的容器端口，默认为2345
      # - XL_DASHBOADR_USER=xunlei
      # - XL_DASHBOADR_PASSWORD=xunlei
      # 设置迅雷WebUI的访问账号密码，可以不设，预设为xunlei
      - XL_UID=1000
      - XL_GID=100
      # 迅雷的用户、用户组权限
      # 用户和用户组权限，ssh中使用“id 用户名”查看，用户组一般为100(users)
      # 第一个用户而言，群晖为1026，新绿联为1001，linux类系统为1000，后续用户均+1
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 2345:2345/tcp
      # WebUI 端口
    restart: always
    # 重启策略
