# 官方文档
# https://github.com/AlistTeam
# https://hub.docker.com/r/xhofe/alist
# alist被卖了，详情见下链接。暂时锁版本为3.40，等后续观望，可以follow/fork/star 这个组织后续项目 https://github.com/AlistTeam
# https://linux.do/t/topic/714827
# https://github.com/AlistGo/alist/issues/8649

## 3.25.0以上版本将密码改成加密方式存储的hash值，无法直接反算出密码，如果忘记了密码只能通过重新 随机生成 或者 手动设置
# 随机生成一个密码，`admin`为账号名，注意替换
# docker exec -it alist ./alist admin random
# 手动设置一个密码，`admin`为账号名，`NEW_PASSWORD`是指你需要设置的密码，注意替换
# docker exec -it alist ./alist admin set NEW_PASSWORD

# AList 问答
# https://alistgo.com/zh/faq/why.html
# WebDAV
# https://alistgo.com/zh/guide/webdav.html
# S3
# https://alistgo.com/zh/guide/advanced/s3.html
# FTP / SFTP
# https://alistgo.com/zh/guide/advanced/ftp.html
# 更多 高级设置
# https://alistgo.com/zh/guide/advanced

---
version: "3"
# 最后编辑时间：2025-06-11
services:
  alist:
    image: xhofe/alist:v3.40.0-ffmpeg
    # 镜像地址
    # alist疑似被售，暂时先将alist锁为3.40版本
    container_name: alist
    # 容器名字
    hostname: alist
    # 主机名
    # privileged: true
    # 特权模式，赋予容器几乎与主机相同的权限
    volumes:
      - /vol1/1000/docker/alist:/opt/alist/data
      # 配置文件目录
      - /vol1:/vol1
      # 映射本地其他路径使其可以访问，可以自定义多个

      # - 【这里替换为你的aria2离线下载目录】:/opt/alist/data/temp/aria2
      # - 【这里替换为你的qbittorrent离线下载目录】:/opt/alist/data/temp/qBittorrent
      # 出处 https://alistgo.com/zh/guide/advanced/offline-download.html
      # 注意需要额外部署一个aria2
      
    environment:
      - PUID=0
      - PGID=0
      # 给最高权限，直接让它可以访问到你的全部东西，注意要做好映射
      - UMASK=022
      # 默认创建新文件的权限，一般写022
      - TZ=Asia/Shanghai
      # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 5244:5244/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
