# 官方文档
# https://hub.docker.com/r/lanol/filecodebox
# https://github.com/lanol/filecodebox

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  filecodebox:
    image: lanol/filecodebox:beta
    # 镜像地址
    container_name: filecodebox
    # 容器名字
    hostname: filecodebox
    # 主机名
    volumes:
      - /share:/app/data
      # 数据目录
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
   #  ports:
      # - 12345:12345/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3