# 官方文档
# https://github.com/cloudflare/cloudflared
# https://hub.docker.com/r/cloudflare/cloudflared
# https://www.cloudflare.com

# 带443端口，可用https，但是不要指望速度多块，大约200kb/s，适合简单的访问，管理

---
version: "3"
# 最后编辑时间：2025-06-04
services:
    cloudflared:
      image: cloudflare/cloudflared:latest
      # 镜像地址
      container_name: cloudflared
      # 容器名字
      hostname: cloudflared
      # 主机名
      network_mode: host
      # 不存在webui，这一条网络模式仅用于不然它创建一个私有网段，强迫症而已
      restart: always
      # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
      command: tunnel --no-autoupdate run --token
        qwertyuiopasdfghjklzxcvbnm1234567890
        # 上一行的字符串，修改为 cloudflare zero-tunnel 的 token

    labels:
      icon: http://IP:PORT/i/user_01/cloudflare_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://www.cloudflare.com
      # 不存在WebUI，链接为官方网站
      net.unraid.docker.icon: /mnt/user/LOGO/cloudflare_A.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
