# 官方文档
# https://hub.docker.com/r/halcyonazure/lsky-pro-docker
# https://www.lsky.pro

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  lsky:
    image: halcyonazure/lsky-pro-docker:latest
    # 镜像地址
    container_name: lsky
    # 容器名字
    hostname: lsky
    # 主机名
    environment:
      - WEB_PORT=8389
      # 自定义WebUI端口号，默认为8089
      - HTTPS_PORT=8388
      # 默认为8088，由于用host模式可能会导致与其他docker容器产生端口冲突，因此修改掉
      ##############################
      # 以下信息在初始化安装的时候就可以填写，如果后续需要修改，可以在这里修改
      #
      # - DB_CONNECTION=【数据库类型】
      # 关联的数据库类型，可选sqlite,mysql,postgresql
      # - DB_HOST=【IP地址】
      # - DB_PORT=【对应的端口】
      # 关联的数据库的IP地址和端口，预设端口mariadb/mysql为3306，postgresql为5432
      # - DB_DATABASE=lsky
      # - DB_USERNAME=lsky
      # - DB_PASSWORD=lsky
      # 关联的数据库的子数据库的名字、账号、密码，这里预设是lsky
      # - REDIS_HOST=【IP地址】
      # - REDIS_PORT=【对应的端口】
      # - REDIS_PASSWORD=【redis的访问密码，如果有】
      # 关联的redis的子IP地址和端口，密码(如果有)，预设端口为6379
      # 
      ##############################
    volumes:
      - /Volume1/docker/lsky:/var/www/html
      # 数据文件目录
      - 【用来存放你的数据的地方】/兰空图床:/var/www/html/storage/app/uploads
      # 图片上传目录
    # network_mode: bridge
    network_mode: host
    # 推荐自定义容器端口，然后使用host模式
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 8089:8089/tcp
      # WebUI http 端口
      # - 8089:8089/tcp
      # WebUI https 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
