# 官方文档
# https://hub.docker.com/r/hedgedoc/hedgedoc
# https://hub.docker.com/r/linuxserver/hedgedoc
# https://docs.linuxserver.io/images/docker-hedgedoc

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  hedgedoc:
    image: linuxserver/hedgedoc:latest
    # 镜像地址
    container_name: hedgedoc
    # 容器名字
    hostname: hedgedoc
    # 主机名
    volumes:
      - /volume1/docker/hedgedoc/config:/config
      # 配置文件目录
      - /volume1/docker/hedgedoc/uploads:/hedgedoc/public/uploads
      # 文件上传目录
    environment:
      - DB_HOST=【IP】
      - DB_PORT=【PORT】
      # 数据库地址，端口，推荐用mariadb
      - DB_NAME=hedgedoc
      - DB_USER=hedgedoc
      - DB_PASS=hedgedoc
      # 子数据库名字，用户名，密码，预设为hedgedoc
      - CMD_PORT=3110
      # 自定义容器端口，默认为3000，预设为3110，因为3000端口有别的要用
      - CMD_ALLOW_ANONYMOUS=false
      # 是否允许任何人匿名创建md
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      # 是否允许任何人编辑
      - CMD_ALLOW_EMAIL_REGISTER=true
      # 是否允许邮箱注册
      - CMD_DEFAULT_PERMISSION=protected
      # 文档默认权限
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 3110:3110/tcp
      # WebUI http端口，要和变量设置的对应
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
