# 官方文档
# https://hub.docker.com/r/msterzhang/onelist
# https://github.com/msterzhang/onelist
# https://xiaoyi.vc/onelist.html

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  onelist:
    image: msterzhang/onelist:latest
    # 镜像地址
    container_name: onelist
    # 容器名字
    hostname: onelist
    # 主机名
    volumes:
      - /volume1/Docker/onelist:/config
      # 数据存储目录
    environment:
      - API_PORT=5245
      # 自定义WebUI端口
      - UserEmail=onelist@cheems.com
      - UserPassword=新建一个密码
      # 初始化管理员邮箱和密码，邮箱随便写
      - PUID=1000
      - PGID=100
      # 用户和用户组权限，ssh中使用“id 用户名”查看，用户组一般为100(users)
      # 第一个用户而言，群晖为1026，新绿联为1001，linux类系统为1000，后续用户均+1
      - UMASK=022
      # 默认创建新文件的权限，一般写022
      - TZ=Asia/Shanghai
      # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 5245:5245/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3