# 官方文档
# https://github.com/acgnhiki/blrec
# https://hub.docker.com/r/acgnhiki/blrec

---
version: "3"
# 最后编辑时间：2025-5-12
services:
  blrec:
    image: acgnhiki/blrec:latest
    # 镜像地址
    container_name: blrec
    # 容器名字
    hostname: blrec
    # 主机名
    command: 
        -c /cfg/settings.toml
        # --api-key bili2233
        # 第一条是选中的setting.toml，照抄，可以在WebUI上修改配置文件内容
        # 这是访问密码，可以不设置，默认不启用
    volumes:
      - /mnt/unas/data/docker/blrec/cfg:/cfg
      # 配置文件目录
      - /mnt/unas/data/docker/blrec/log:/log
      # 日志文件目录
      - 【这里替换为你录播的存放目录】:/rec
      # 录像存放目录
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 2233:2233/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
