# 官方文档
# https://surveyking.cn
# https://hub.docker.com/r/surveyking/surveyking
# https://gitee.com/surveyking/surveyking

# 官方更新日志
# https://surveyking.cn/open-source/changelog
# 使用手册
# https://surveyking.cn/help/quickstart

# 初始账号：admin
# 初始密码：123456
# 官方镜像仅支持到1.31版，若需要开源版部署，需要加入Q群92878557（2024-05-17最新分群），群文件中获取
# 个人分享
# https://www.123pan.com/s/YuAUVv-UT1nA.html

# 官方版本只支持x86版本且需要本地编译镜像，故推荐使用该镜像：mrxianyu/surveyking，该镜像支持x86和arm64位系统，截至2024年05月17日为1.6.0版本所编译的镜像，但可以通过映射官方最新版的jar文件，从而进行升级
# https://hub.docker.com/r/mrxianyu/surveyking

# 部署步骤
# 第一步，准备好数据库文件（必须），jar文件（可选）
# 第二步，在mysql中新建surveyking的子数据库，类型选择utf8mb4_unicode_ci
# 第三步，给子数据设置一个子账号，模板预设的账号密码均为surveyking
# 第四步，将下载的数据库文件init-mysql.sql，导入到surveyking数据库内
# 第五步，修改好compose，然后执行

---
version: "3"
# 最后编辑时间：2024-05-16
services:
  surveyking:
    image: mrxianyu/surveyking:latest
    # 镜像地址
    container_name: surveyking
    # 容器名字
    hostname: surveyking
    # 主机名
    volumes:
      # - /mnt/unas/data/docker/surveyking/surveyking-v1.7.2.jar:/app/surveyking.jar
      # jar文件映射，可不映射，截至至2024-05-17，镜像内的版本为1.6.0版本，自行获取新版jar文件并映射就可以更新到官方最新版本
      - /mnt/unas/data/docker/surveyking/files:/app/files
      # 数据目录
      - /mnt/unas/data/docker/surveyking/logs:/app/logs
      # 日志目录    environment:
      - SERVER_PORT=1991
      # 自定义容器的WebUI端口
      - DB_URL=jdbc:mysql://【IP:PORT】/surveyking
      # 数据库地址，默认模板：jdbc:mysql://mysql:3306/surveyking
      - MYSQL_USER=surveyking
      - MYSQL_PASS=surveyking
      # 子数据库账号、密码，预设为surveyking
    # network_mode: bridge
    network_mode: host
    # 推荐自定义容器端口，然后直接使用host模式
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 1991:1991/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
