# 官方文档
# https://sillytavern.app
# https://docs.sillytavern.app/installation/docker
# https://github.com/SillyTavern/SillyTavern

# 教程
# https://post.smzdm.com/p/al8nke5g
# https://www.hqshi.cn/info/knowledge/sillytavern-guide

# Linux 系统一键安装脚本
# https://github.com/mxw13579/silly-tavern-docker-starts

---
version: "3"
# 最后编辑时间：2025-02-26
services:
  sillytavern:
    image: ghcr.io/sillytavern/sillytavern:latest
    # 镜像地址
    container_name: sillytavern
    # 容器名字
    hostname: sillytavern
    # 主机名
    volumes:
      - /mnt/unas/data/docker/sillytavern/config:/home/node/app/config
      # 配置文件目录
      - /mnt/unas/data/docker/sillytavern/data:/home/node/app/data
      # 用户数据目录data，插件目录plugins
      - /mnt/unas/data/docker/sillytavern/plugins:/home/node/app/plugins
      # 官方插件目录
      - /mnt/unas/data/docker/sillytavern/extensions:/home/node/app/public/scripts/extensions/third-party
      # 第三方插件目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 8000:8000/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
