# 官方文档
# https://hub.docker.com/dreamacro/clash
# https://hub.docker.com/haishanh/yacd
# 部署教程
# https://zhanghongyun.cn/article/detail
# https://wayne-wang66.github.io/blog/posts/使用 Docker 运行 Clash.html

# 请自备魔法

---
version: "3"
# 最后编辑时间：2024-10-18
services:
  clash:
    image: dreamacro/clash:latest
    # 镜像地址
    container_name: clash
    # 容器名字
    hostname: clash
    # 主机名
    volumes:
      - /mnt/unas/data/clash/config.yaml:/root/.config/clash/config.yaml
      # 配置文件目录，部署启动前先把config.yaml存到本地内
    environment:
        - TZ=Asia/Shanghai
        # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # 注意：minio用到9090端口，如果都要部署，建议修改config.yaml中的9090端口再用host模式，或者使用bridge模式把9090端口改成别的，只要保证不冲突即可
    # ports:
      # - 7890:7890/tcp
      # http/https 监听端口
      # - 7891:7891/tcp
      # 7891 为 socks5 监听端口
      # - 9090:9090/tcp
      # 后端地址的端口
      # 该镜像无WebUI
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3

# 以下不需要部署，个人感觉没用，打开webui一会儿会自动回退到选择后端的界面

#  clash-web:
#    image: haishanh/yacd:latest
    # 镜像地址
#    container_name: clash-web
    # 容器名字
#    hostname: clash-web
    # 主机名
#    environment:
#      - YACD_DEFAULT_BACKEND=http://127.0.0.1:9090
      # yacd默认连接clash的后端地址，默认为127.0.0.1:9090，一般yaml内后端的默认端口就是9090
#      - TZ=Asia/Shanghai
      # 时区
#    network_mode: bridge
    # 80端口被占用，不能用host
#    ports:
#      - 5080:80/tcp
      # WebUI 端口
#    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
