# 官方文档
# https://docs.linuxserver.io/images/docker-transmission
# https://hub.docker.com/r/linuxserver/transmission
# PT玩家看站规！！！
# PT玩家看站规！！！
# PT玩家看站规！！！

# 需要创建好一个基于macvlan，名为br0的docker网络，具体看 README / WHAT'S_OLD 中2025-01-04的更新内容
# 适用于让 QB/TR/其他docker容器 具有一个独立IP地址，添加其IP至魔法网络的黑名单中，不让其走魔法网络，从而避免标记为盒子
# 下方的 br0 为自定义网络的名字，请根据实际情况修改
# 注意：将会直接使用容器的端口进行访问，transmission默认的容器端口为9091，如需修改WebUI的端口，到/config/setting.json中第54行的"rpc-port": 9091的端口改为自定义端口

---
version: "3"
# 最后编辑时间：2025-01-05
services:
  transmission:
    image: linuxserver/transmission:latest
    # 镜像地址，如需改用3.x版本，把latest改为version-3.00-r8
    container_name: transmission
    # 容器名字
    hostname: transmission
    # 主机名
    # privileged: true
    # 特权模式，赋予容器几乎与主机相同的权限
    volumes:
      - /mnt/unas/data/docker/transmission:/config
      # 配置文件目录
      - /mnt/unas/data/downloads:/downloads
      # 默认下载目录
      # - /mnt/unas/data/docker/TR种子监控自动下载目录:/watch
      # 种子监控自动下载目录，非必须，用于把种子放到目录内后，自动添加下载任务
      # - 【这里替换为你想映射到TR内的路径】:/【这里替换为你想映射到TR内的路径】
      # 可以自定义，可以写多个，这里如果你理解了映射是什么，就会明白是什么意思，如果不会，别写
      # 如果你不理解映射，不要修改tr设置里的下载目录，保持/downloads，要分类下载就写在/downloads后面！！！如/downloads/电影
      # 如果你不理解映射，不要修改tr设置里的下载目录，保持/downloads，要分类下载就写在/downloads后面！！！如/downloads/电影
      # 如果你不理解映射，不要修改tr设置里的下载目录，保持/downloads，要分类下载就写在/downloads后面！！！如/downloads/电影
    environment:
      - TRANSMISSION_WEB_HOME=/config/webui
      # WEBUI主页路径，写容器路径，用于放汉化文件
      # 4.x版本的汉化文件下载地址：https://github.com/ronggang/transmission-web-control
      # 将 "/src" 这个文件夹里的东西放到 "/config/webui" 内即可
      - USER=cheems
      - PASS=cheems
      # TR账号密码，预设为cheems，记住一定要修改密码，否则后果自负
      - PEERPORT=14569
      # 自定义peer传输端口
      - PUID=0
      - PGID=0
      # 用户和用户组权限，ssh中使用“id 用户名”查看，用户组一般为100(users)
      # 第一个用户而言，群晖为1026，新绿联为1001，linux类系统为1000，后续用户均+1
      # 如果出现无法下载的情况，改为0
      - UMASK=022
      # 默认创建新文件的权限，一般写022
      - TZ=Asia/Shanghai
      # 时区
    networks:
      br0:
        ipv4_address: 192.168.1.234
        # 设置一个没有占用的局域网ip地址，默认预设为192.168.1.234，请根据实际情况修改
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3

# 以下照抄
networks:
    br0:
      external: true
      name: br0
