# 官方文档
# https://bitwarden.com
# https://hub.docker.com/r/vaultwarden/server
# 广域网中使用，需要https，建议使用lucky/npm进行反代

---
version: "3"
# 最后编辑时间：2024-08-03
services:
  vaultwarden:
    image: vaultwarden/server:latest
    # 镜像地址
    container_name: vaultwarden
    # 容器名字
    hostname: vaultwarden
    # 主机名
    volumes:
      - 【这里替换为你的docker数据存放目录】/vaultwarden:/data
      # 配置文件目录
    environment:
      - ADMIN_TOKEN=【管理者密钥，写复杂点增加安全性】
      # 管理者密钥，自定义一个密钥，访问 http://IP:PORT/admin 中使用
      - SIGNUPS_ALLOWED=true
      # 是否允许登录，默认为true
      - INVITATIONS_ALLOWED=true
      # 是否允许邀请，默认为true
      - WEBSOCKET_ENABLED=false
      # websocket启动，默认为false
      - TZ=Asia/Shanghai
      # 时区
    network_mode: bridge
    # 80端口被占用，不能用host
    ports:
      - 4743:80/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/vaultwarden_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:80]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/vaultwarden.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑