# 官网
# https://pixman.io
# 官方文档
# https://pixman.io/topics/17
# https://hub.docker.com/r/pixman/pixman

---
version: '3'
# 最后编辑时间：2024-07-09
services:
  pixman:
    image: pixman/pixman:latest
    # 镜像地址，arm/v7 架构系统请使用 pixman/pixman-armv7 该镜像
    container_name: pixman
    # 容器名字
    hostname: pixman
    # 主机名
    volumes:
      - /mnt/user/appdata/pixman:/app/app/data/m3u
      # 导入外部的 m3u 文件，从而通过 http://ip:port/your.m3u 访问
    # environment:
      # - http_proxy=http://【IP:PORT】
      # - https_proxy=http://【IP:PORT】
      # 如果某些域名无法访问，可以使用参数设置代理，注意替换成你自己代理的 ip 和端口
      # - MYTVSUPER_TOKEN=
      # 如果你需要访问 MytvSuper 直播源，那需要设置 MYTVSUPER_TOKEN 环境变量
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 5050:5000/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
