# 官方文档
# https://www.nginxwebui.cn
# https://github.com/cym1102/nginxWebUI

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  nginx-webui:
    image: cym1102/nginxwebui:latest
    # 镜像地址
    container_name: nginx-webui
    # 容器名字
    hostname: nginx-webui
    # 主机名
    volumes:
      - /mnt/user/appdata/nginxWebUI:/home/nginxWebUI
      # 配置文件目录
    environment:
      - BOOT_OPTIONS=--server.port=9090
      # 9090为默认WebUI端口，可以自定义
    network_mode: host
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:9090]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/nginx-webui.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑