# 官网
# https://about.gitea.com
# 官方文档
# https://docs.gitea.com/zh-cn
# https://hub.docker.com/r/gitea/gitea
# https://docs.gitea.com/installation/install-with-docker

---
version: "3"
# 最后编辑时间：2024-05-11
services:
  gitea:
    image: gitea/gitea:latest
    # 镜像地址
    container_name: gitea
    # 容器名字
    hostname: gitea
    # 主机名
    volumes:
      - /mnt/user/appdata/gitea:/data
      # 数据目录
    environment:
      - USER_UID=1000
      - USER_GID=100
      # 用户和用户组权限，ssh中使用“id 用户名”查看，用户组一般为100(users)
      # 第一个用户而言，群晖为1026，新绿联为1001，linux类系统为1000，后续用户均+1
      - HTTP_PORT=3200
      # HTTP 监听端口，默认为3000
      - SSH_LISTEN_PORT=4222
      # 内部的 SSH 服务器的端口，默认为22
      # - ROOT_URL="http://【IP:PORT】"
      # 覆盖自动生成的公共 URL。如果内部 URL 和外部 URL 不匹配（例如在 Docker 中），这很有用。
      # IP:PORT为宿主机的IP和端口
    network_mode: host
    restart: always
    # 重启策略
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3200]
      # 适用于unraid的WebUI打开，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/16-LOGO/icon/gitea.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
