# 官方文档
# https://hub.docker.com/r/privoce/vocechat-server

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  vocechat:
    image: privoce/vocechat-server:latest
    # 镜像地址
    container_name: vocechat
    # 容器名字
    hostname: vocechat
    # 主机名
    network_mode: bridge
    # 推荐使用bridge模式，3000有别的docker镜像要用
    ports:
      - 3040:3000/tcp 
      # WebUI http端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3000]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/vocechat-server.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
