# 官方文档
# https://hub.docker.com/r/hedgedoc/hedgedoc
# https://hub.docker.com/r/linuxserver/hedgedoc
# https://docs.linuxserver.io/images/docker-hedgedoc

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  hedgedoc:
    image: linuxserver/hedgedoc:latest
    # 镜像地址
    container_name: hedgedoc
    # 容器名字
    hostname: hedgedoc
    # 主机名
    volumes:
      - /mnt/user/appdata/hedgedoc:/config
      # 配置文件目录
      - /mnt/user/hedgedoc:/hedgedoc/public/uploads
      # 文件上传目录
    environment:
      - DB_HOST=【IP】
      - DB_PORT=【PORT】
      # 数据库地址，端口，推荐用mariadb
      - DB_NAME=hedgedoc
      - DB_USER=hedgedoc
      - DB_PASS=hedgedoc
      # 子数据库名字，用户名，密码，预设为hedgedoc
      - CMD_PORT=3310
      # 自定义容器端口，默认为3000
      - CMD_ALLOW_ANONYMOUS=false
      # 是否允许任何人匿名创建md
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      # 是否允许任何人编辑
      - CMD_ALLOW_EMAIL_REGISTER=true
      # 是否允许邮箱注册
      - CMD_DEFAULT_PERMISSION=protected
      # 文档默认权限
    network_mode: host
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3000]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/hedgedoc.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑