# 官方文档
# https://hub.docker.com/r/frooodle/s-pdf
# https://github.com/Stirling-Tools/Stirling-PDF

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  s-pdf:
    image: frooodle/s-pdf:latest
    # 镜像地址
    container_name: s-pdf
    # 容器名字
    hostname: s-pdf
    # 主机名
    volumes:
      - /mnt/user/appdata/s-pdf/configs:/configs
      # 配置文件目录
      - /mnt/user/appdata/s-pdf/logs:/logs
      # 日志文件目录
      - /mnt/user/photo:/usr/share/tessdata
      # 图片上传目录
    network_mode: bridge
    # 推荐使用bridge模式，8000有别的docker镜像要用
    ports:
      - 8660:8000/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:8000]
      net.unraid.docker.icon: /mnt/user/LOGO/stirling-pdf.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑