# 官方文档
# https://v2raya.org
# https://v2raya.org/docs/prologue/introduction
# https://v2raya.org/docs/prologue/installation/docker
# https://hub.docker.com/r/mzz2017/v2raya

# 本模板适合对于使用 macOS 或其他不支持 host 模式的环境，在该情况下无法使用全局透明代理，或者你不希望使用全局透明代理

---
version: "3"
# 最后编辑时间：2025-05-12
services:
  v2raya:
    image: mzz2017/v2raya:latest
    # 镜像地址
    container_name: v2raya
    # 容器名字
    hostname: v2raya
    # 主机名
    volumes:
      - 【这里替换为你的docker数据存放目录】/v2raya/v2raya:/etc/v2raya
      # 配置文件目录
      
      - /etc/resolv.conf:/etc/resolv.conf
      # 请确报有这条路径，有这个文件，需不然会创建成文件夹
      # 上面这条如果 /etc 内没有或不会进去，新建 resolv.conf 文件，可以写下面这条，注意新建好 resolv.conf 文件，这是文件映射
      # - 【这里替换为你的docker数据存放目录】/v2raya/resolv.conf:/etc/resolv.conf

    # network_mode: bridge
    network_mode: host
    # 可host也可bridge，如果端口冲突，预设使用host

    # bridge时，在同一个docker容器子网bridge中，其他容器可以通过 172.17.0.1:[201710-20172] 进行访问，例如emby/JF变量中的网络代理参数
    # host时，在同一个docker容器子网host中，其他容器可以通过 127.0.0.1:[201710-20172] 进行访问，例如emby/JF变量中的网络代理参数
    # 但是不在统一docker容器子网的，无法通过以上方式通讯，可通过以下方式
    # 对于局域网中其他设备，你直接写 服务器的IP:[201710-20172] 进行访问，例如emby/JF变量中的网络代理参数

      # - 2017:2017/tcp
      # WebUI 端口：2017
      # - 20170-20172:20170-20172/tcp
      # sock 代理端口：20170
      # http 代理端口：20171
      # http 代理端口(带分流规则)：20172
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
