# 官方文档
# https://www.nginxwebui.cn
# https://github.com/cym1102/nginxWebUI

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  nginx-webui:
    image: cym1102/nginxwebui:latest
    # 镜像地址
    container_name: nginx-webui
    # 容器名字
    hostname: nginx-webui
    # 主机名
    volumes:
      - /Volume1/User/docker/nginxWebUI:/home/nginxWebUI
      # 配置文件目录
    environment:
      - BOOT_OPTIONS=--server.port=9090
      # 9090为默认WebUI端口，可以自定义
    network_mode: host
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3