# 官方文档
# http://hub.docker.com/lobehub/lobe-chat
# https://lobehub.com
# https://lobehub.com/zh/blog/5-lobe-chat-web-ui-recommendation

---
version: "3"
# 最后编辑时间：2024-05-20
services:
  lobe-chat:
    image: lobehub/lobe-chat
    # 镜像地址
    container_name: lobe-chat
    # 容器名字
    hostname: lobe-chat
    # 主机名
    # environment:
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 3210:3210/tcp
      # WebUI 端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
      