# 官方文档
# https://github.com/amtoaer/bili-sync
# https://hub.docker.com/r/amtoaer/bili-sync-rs
# 部署教程
# https://blog.hesuisui.top/archives/Docker-Bili-Sync
# 部署前，请先把配置文件弄好再启动启动

# 配置文件步骤简要说明
# 步骤1：打开，浏览器，按F12，点击上方的"控制台"，打开b站，退出登录，然后重新登录，一定要重新登录
# 步骤2：在最下方文本空白处输入“允许粘贴”，回车键，然后复制粘贴"window.localStorage.ac_time_value"改内容进去，回车键，即可获取到"ac_time_value"的值，这个值只有刚登录才能获取到
# 步骤3：点击最上方的"应用程序"，如果没有，点一下加号，点击左侧的"Cookie","https://www.bilibili.com/"
# 步骤4：在右侧表格中分别获取到"sessdata","bili_jct","buvid3","dedeuserid"的值
# 步骤5：将"sessdata","bili_jct","buvid3","dedeuserid","ac_time_value"这5个值写进 config.toml 中
# 步骤6：剩余的步骤就不说了，看教程吧，收藏夹的id可以打开自己的收藏夹，在地址栏上的数字就是收藏夹id号码

---
version: "3"
# 最后编辑时间：2024-04-23
services:
  bili-sync-rs:
    image: amtoaer/bili-sync-rs:latest
    # 镜像地址
    container_name: bili-sync-rs
    # 容器名字
    hostname: bili-sync-rs
    # 主机名
    volumes:
      - 【这里替换为你的docker数据存放目录】/bili-sync-rs:/app/.config/bili-sync
      # 配置目录
      - 【这里替换为你的数据存放目录】/B站收藏同步:/downloads
      # 默认下载目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
    network_mode: host
    # 不存在webui，这一条网络模式仅用于不然它创建一个私有网段，强迫症而已
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      # 该镜像只在后台运行，无WebUI 
      icon: http://IP:PORT/i/user_01/bili-sync_A.png
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: /mnt/user/LOGO/bili-sync.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
