# 官网
# https://pixman.io
# 官方文档
# https://pixman.io/topics/17
# https://hub.docker.com/r/pixman/pixman
# https://github.com/chinggirltube/M3U-Proxy

---
version: '3'
# 最后编辑时间：2024-07-09
services:
  pixman:
    image: pixman/pixman:latest
    # 镜像地址，arm/v7 架构系统请使用 pixman/pixman-armv7 该镜像
    container_name: pixman
    # 容器名字
    hostname: pixman
    # 主机名
    volumes:
      - 【这里替换为你的docker数据存放目录】/pixman:/app/app/data/m3u
      # 导入外部的 m3u 文件，从而通过 http://ip:port/your.m3u 访问
    # environment:
      # - http_proxy=http://【IP:PORT】
      # - https_proxy=http://【IP:PORT】
      # 如果某些域名无法访问，可以使用参数设置代理，注意替换成你自己代理的 ip 和端口
      # - MYTVSUPER_TOKEN=
      # 如果你需要访问 MytvSuper 直播源，那需要设置 MYTVSUPER_TOKEN 环境变量
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 5050:5000/tcp
      # WebUI 端口，注意群晖的WebUI端口为5000，要用要改成bridge+别的端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_1/pixman_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:5000]
      net.unraid.docker.icon: /mnt/user/LOGO/pixman.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
