# 官方文档
# https://roon.app
# https://community.roonlabs.com/c/roon/software-release-notes/18
# https://hub.docker.com/r/gz1903/roonserver

# 注意：仅支持amd64

version: '3'
# 最后编辑时间：2025-04-16
services:
 roon:
    image: gz1903/roonserver:latest
    # 镜像名字
    container_name: roon
    # 容器名字
    hostname: roon
    # 主机名
    privileged: true
    # 特权模式，赋予容器几乎与主机相同的权限
    volumes:
      # - 【这里替换为你的docker数据存放目录】/roon:/usr/bin/RoonServer
      # 你的自定义 RoonServer 文件，默认不需要，除非你要自定义安装
      - 【这里替换为你的音乐存放目录】/roon:/root/music
      # 音乐存放目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 9100:9100/tcp
      # 访问端口，不存在WebUI管理页面
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/roon.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://hub.docker.com/r/gz1903/roonserver
      # 不存在WebUI管理页面，这里修改为项目地址
      net.unraid.docker.icon: /mnt/user/LOGO/roon.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
