# 官方文档
# https://hub.docker.com/r/hrustdesk/rustdesk-server
# https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/

# 默认情况下，hbbs 在21114(TCP，用于 web 控制台，只有 Pro 版本可用)、21115(TCP)、21116(TCP/UDP)和21118(TCP)上监听，hbbr 在21117(TCP)和21119(TCP)上监听。
# 确保在防火墙中打开这些端口。请注意，对于 TCP 和 UDP 都应该启用21116。

# rustdesk-api-serever的官方文档
# https://github.com/kingmo888/rustdesk-api-server

# 21114 用于 rustdesk-api-serever 的WebUI使用，非必要
# 21115 用于 NAT 类型测试
# 21116/UDP 用于 ID 注册和心跳服务
# 21116/TCP 用于 TCP打洞和连接服务
# 21117 用于中继服务
# 21118和21119用于支持 web 客户端。如果您不需要 Web 客户端(21118,21119)支持，可以禁用相应的端口。

---
version: "3"
# 最后编辑时间：2025-02-28
services:
  rustdesk-hbbs-host:
    image: rustdesk/rustdesk-server:latest
    # 镜像地址
    container_name: rustdesk-hbbs-host
    # 容器名字
    hostname: rustdesk-hbbs-host
    # 主机名
    command: hbbs # -r 192.168.1.42:42117
    # 如果使用host模式则不需要去掉#号注释，否则去掉#号并在-r后面输入NAS的IP和rustdesk-hbbr的21117的映射端口
    volumes:
      - /mnt/emmc/docker/rustdesk-host:/root
      # 配置文件目录
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 21115:21115/tcp
      # 用于 NAT 类型测试
      # - 21116:21116/tcp
      # 用于 TCP打洞和连接服务
      # - 21116:21116/udp
      # 用于 ID 注册和心跳服务
      # - 21117:21117/tcp
      # 用于中继服务
      # - 21118:21118/tcp
      # 用于支持 web 客户端(http)
      # - 21119:21119/tcp
      # 用于支持 web 客户端(https)
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    depends_on:
      - rustdesk-hbbr-host

  rustdesk-hbbr-host:
    image: rustdesk/rustdesk-server:latest
    # 镜像地址
    container_name: rustdesk-hbbr-host
    # 容器名字
    hostname: rustdesk-hbbr-host
    # 主机名
    command: hbbr
    volumes:
      - /mnt/emmc/docker/rustdesk-host:/root
      # 配置文件目录
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 21117:21117/tcp
      # 用于中继服务
      # - 21119:21119/tcp
      # 用于支持 web 客户端(https)
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3

# 非必要
  rustdesk-api-server:
    image: ghcr.io/kingmo888/rustdesk-api-server:latest
    # 镜像地址
    container_name: rustdesk-api-server
    # 容器名字
    hostname: rustdesk-api-server
    # 主机名
    volumes:
      - /mnt/emmc/docker/rustdesk-host:/rustdesk-api-server/db
      # 宿主机数据库挂载目录，要和上面对应一致，目录内要有db文件
    environment:
      # - CSRF_TRUSTED_ORIGINS=http://【域名解析公网IP的地址】:21114 
      # 防跨域信任来源，可选，默认关闭验证；如需开启填写你的访问地址 http://yourdomain.com:21114，如需关闭验证请删除此变量，而不是留空
      # - ID_SERVER=【域名解析公网IP的地址】
      # Web控制端使用的ID服务器，可选，默认为和API服务器同主机。可自定义如 yourdomain.com
      - LANGUAGE_CODE=zh-hans
      # 设置语言为中文
      # - SECRET_KEY=
      # 程序加密秘钥，可选，自定义一串随机字符
      # - HOST=0.0.0.0
      # 绑定服务的IP，默认 0.0.0.0
      - TZ=Asia/Shanghai
      # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 21114:21114/tcp
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
