# 官方文档
# https://hub.docker.com/r/jmal/jmalcloud
# https://github.com/jamebal/jmal-cloud-view
# https://gitee.com/jmal/jmal-cloud-view

# 1. 重置密码
# docker exec -it jmalcloud_mongodb mongo jmalcloud --eval "db.getCollection('user').update({ 'creator': true }, {\$set: { 'password': '1000:c5b705ea13a1221f5e59110947ed806f8a978e955fbd2ed6:22508de12228c34a235454a0caf3bcaa5552858543258e56' }}, { 'multi': false, 'upsert': false })"
# 2. 重启容器
# docker restart jmalcloud_server
# 重置后的密码为: jmalcloud

# 备份数据库
# docker exec -it jmalcloud_mongodb mongodump -d jmalcloud -o /dump/xxx --gzip --quiet
# 恢复数据库
# docker exec -it jmalcloud_mongodb mongorestore -d jmalcloud --dir /dump/xxx --gzip --quiet

# 官方作者的模板几乎写死，注意切勿随意修改

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  jmalcloud:
  # ↑切勿修改
    image: jmal/jmalcloud:latest
    # 镜像地址
    container_name: jmalcloud
    # 容器名字
    hostname: jmalcloud
    # 主机名
    volumes:
      - 【这里替换为你的数据存放目录】/jmalcloud:/jmalcloud
      # 配置目录
      - 【这里替换为你的数据存放目录】:/【这里替换为你的数据存放目录的名字】
      # 映射本地其他路径使其可以访问，可以自定义多个
    environment:
      - MONGODB_URI=mongodb://mongo:27017/jmalcloud
      # mongodb数据库的配置信息，切勿修改
      - TZ=Asia/Shanghai
      # 时区
    ports:
      - 7072:8088/tcp
      # WebUI 端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/jmalcloud.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:8088]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/jmalcloud.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑

########################################

  nginx:
  # ↑切勿修改
    image: jmal/jmalcloud-nginx:latest
    # 镜像地址
    container_name: jmalcloud-nginx
    # 容器名字
    hostname: jmalcloud-nginx
    # 主机名
    environment:
      - TZ=Asia/Shanghai
      # 时区
    ports:
      - 7070:80/tcp
      # 管理页面 端口
      - 7071:8089/tcp
      # 博客页面 端口
      # ↓切勿修改
    depends_on:
      - jmalcloud
      - office
      - drawio-webapp
      # ↑切勿修改
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/jmalcloud-nginx.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: /mnt/user/LOGO/jmalcloud-nginx.png
      net.unraid.docker.webui: http://[IP]:[PORT:80]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑

########################################

  mongo:
  # ↑切勿修改
    image: mongo:4.4
    # 镜像地址，切勿修改
    container_name: jmalcloud-mongodb
    # 容器名字
    hostname: jmalcloud-mongodb
    # 主机名
    command: --wiredTigerCacheSizeGB 0.5
    # 设置缓冲文件大小为0.5G
    volumes:
      # - 【这里替换为你的docker数据存放目录】/jmalcloud/mongodb/data/configdb:/data/configdb
      # 配置目录
      - 【这里替换为你的docker数据存放目录】/jmalcloud/mongodb/data:/data
      # 数据库目录
      - 【这里替换为你的docker数据存放目录】/jmalcloud/mongodb/backup:/dump
      # 备份目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
      # mongodb的访问端口，该镜像无WebUI页面，只需要通过IP:PORT访问即可，预设为44429
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/jmalcloud-mongodb.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: /mnt/user/LOGO/jmalcloud-mongodb.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑

########################################

  office:
  # ↑切勿修改
    image: onlyoffice/documentserver:latest
    # 镜像地址
    container_name: jmalcloud-onlyoffice
    # 容器名字
    hostname: jmalcloud-onlyoffice
    # 主机名
    volumes:
      - 【这里替换为你的docker数据存放目录】/jmalcloud/onlyoffice/data:/var/www/onlyoffice/Data
      # 数据目录
      - 【这里替换为你的docker数据存放目录】/jmalcloud/onlyoffice/lib:/var/lib/onlyoffice
      - 【这里替换为你的docker数据存放目录】/jmalcloud/onlyoffice/log:/var/log/onlyoffice
      # 日志目录
      - 【这里替换为你的docker数据存放目录】/jmalcloud/onlyoffice/redis:/var/lib/redis
      - 【这里替换为你的docker数据存放目录】/jmalcloud/onlyoffice/pgsql:/var/lib/postgresql
      # onlyoffice的redis，pgsql目录
      - 【这里替换为你的docker数据存放目录】/jmalcloud/onlyoffice/rabbitmq:/var/lib/rabbitmq
      # onlyoffice的消息队列
      - 【这里替换为你的docker数据存放目录】/jmalcloud/onlyoffice/custom:/usr/share/fonts/truetype/custom
      # onlyoffice的字体库目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/jmalcloud-onlyoffice.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: /mnt/user/LOGO/jmalcloud-onlyoffice.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑

########################################

  drawio-webapp:
  # ↑切勿修改
    image: jgraph/drawio:latest
    # 镜像地址
    container_name: jmalcloud-drawio
    # 容器名字
    hostname: jmalcloud-drawio
    # 主机名
    environment:
      - TZ=Asia/Shanghai
      # 时区
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/jmalcloud-drawio.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: /mnt/user/LOGO/jmalcloud-drawio.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑

########################################