# 官方文档
# https://github.com/snowdreamtech/frp
# https://github.com/fatedier/frp
# https://github.com/stilleshan/frps
# 镜像地址
# https://hub.docker.com/r/qq918652593/easy-frps
# 软件作者：隔壁小王

# 相关教程
# https://gofrp.org/zh-cn/docs

---
version: "3"
# 最后编辑时间：2026-06-20
services:
  easy-frps:
    image: qq918652593/easy-frps:latest
    # 镜像地址，仅支持amd64
    container_name: easy-frps
    # 容器名字
    volumes:
      - 【这里替换为你的docker数据存放目录】/frp/easy-frps:/app/data
      # 配置文件目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
    network_mode: host
    # 推荐直接使用host网络模式，除非5000端口被占用，例如群晖
    # easy-frps的可视化在线配置面板端口默认为5000，frps仪表盘端口默认为7500，具体看 frps.toml 中的设置
    # 注意
      
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:5000]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      # 这里写的是可视化在线配置面板，内置可直接查看frps仪表盘
      net.unraid.docker.icon: /mnt/user/LOGO/frps.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
