# 官方文档
# https://www.memcached.org
# https://hub.docker.com/_/memcached
# https://www.runoob.com/memcached/memcached-tutorial.html
# https://www.modb.pro/db/1815927947938848768

# Memcached 对比 Redis
# https://zhuanlan.zhihu.com/p/370976423
# https://zhuanlan.zhihu.com/p/671402920

---
version: "3"
# 最后编辑时间：2024-05-06
services:
  memcached:
    image: memcached:latest
    # 镜像地址
    container_name: memcached
    # 容器名字
    hostname: memcached
    # 主机名
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
     # 限制预处理大小，内存大小，线程数量
    network_mode: host
    # 不具备端口，一般都是调用即可，这玩意要配合用
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/it-tools-light.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: /mnt/user/LOGO/it-tools-light.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
