# 官方文档
# https://hub.docker.com/r/linuxserver/jackett
# https://docs.linuxserver.io/images/docker-jackett

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  jackett:
    image: linuxserver/jackett:latest
    # 镜像地址
    container_name: jackett
    # 容器名字
    hostname: jackett
    # 主机名
    volumes:
      - /volume1/docker/jackett:/config
      # 配置目录
      - 【这里替换为你的bt文件存放目录】:/downloads
      # 种子目录
    environment:
      - PUID=1000
      # 用户权限，群晖用户一般写1026，unraid用户写1000，视情况写0，即root
      - PGID=100
      # 用户组权限
      - UMASK=022
      # 默认创建新文件的权限，一般写022
      - TZ=Asia/Shanghai
      # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 9117:9117/tcp
      # WebUI 端口，设置内可以自定义端口号
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/jackett_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:9117]
      net.unraid.docker.icon: /mnt/user/LOGO/jackett.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑