# 官方文档
# https://min.io
# https://hub.docker.com/r/minio/minio
# 部署教程
# https://zhuanlan.zhihu.com/p/684175456

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  minio:
    image: minio/minio:latest
    # 镜像地址
    container_name: minio
    # 容器名字
    hostname: minio
    # 主机名
    command: server /minio --console-address :9090
    # /minio为对象存储的目录
    # 9090为WebUI容器端口
    volumes:
      - /volume1/docker/MinIO:/data
      # 配置文件目录
      - /volume1/MinIO:/minio
      # 对象存储的目录
    environment:
      - PUID=1000
      # 用户权限，群晖用户一般写1026，unraid用户写1000，视情况写0，即root
      - PGID=100
      # 用户组权限
      - UMASK=022
      # 默认创建新文件的权限，一般写022
      - TZ=Asia/Shanghai
      # 时区
      - MINIO_ROOT_USER=这里写你的用户名字
      - MINIO_ROOT_PASSWORD=新建一个密码
      # MINIO的管理者账号和密码
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 9090:9090/tcp
      # WebUI 端口
      # - 9000:9000/tcp
      # api 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/minio_D.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:9090]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/minio.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑