# 官方文档
# https://hub.docker.com/r/halcyonazure/lsky-pro-docker
# https://www.lsky.pro

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  lsky:
    image: halcyonazure/lsky-pro-docker:latest
    # 镜像地址
    container_name: lsky
    # 容器名字
    hostname: lsky
    # 主机名
    environment:
      - WEB_PORT=8389
      # 自定义WebUI端口号，默认为8089
      - HTTPS_PORT=8388
      # 默认为8088，由于用host模式可能会导致与其他docker容器产生端口冲突，因此修改掉
    volumes:
      - /share/container-station-data/lsky:/var/www/html
      # 数据文件目录
      - /share/Multimeeida/兰空图床:/var/www/html/storage/app/uploads
      # 图片上传目录
    network_mode: host
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3