# 官方文档
# https://os.tenfell.cn
# https://os.tenfell.cn/doc/guide/arrange/docker.html
# https://hub.docker.com/r/fs185085781/webos

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  webos:
    image: fs185085781/webos:latest
    # 镜像地址
    container_name: webos
    # 容器名字
    hostname: webos
    # 主机名
    volumes:
      - /share/container-station-data/webos/apps:/webos/web/apps
      # app目录
      - /share/container-station-data/webos/rootPath:/webos/api/rootPath
      # 配置文件目录
      - /share/Public/webosMnt:/webosMnt
      # - 【这里替换为你的数据存放目录】:/【这里替换为你的数据存放目录的名字】
      # 数据目录
      # 可以自定义多个
    environment:
      - PUID=1000
      - PGID=100
      # 用户和用户组权限，ssh中使用“id 用户名”查看，用户组一般为100(users)
      # 第一个用户而言，群晖为1026，新绿联为1001，linux类系统为1000，后续用户均+1
      - UMASK=022
      # 默认创建新文件的权限，一般写022
      - TZ=Asia/Shanghai
      # 时区
    network_mode: bridge
    # network_mode: host
    # 有别的docker可能会用到8088，推荐bridge模式
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    ports:
      - 8188:8088/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
