# 官方文档
# https://hub.docker.com/r/vaultwarden/server

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  vaultwarden:
    image: vaultwarden/server:latest
    # 镜像地址
    container_name: vaultwarden
    # 容器名字
    hostname: vaultwarden
    # 主机名
    volumes:
      - /share/container-station-data/vaultwarden:/data
      # 配置文件目录
    environment:
      - SIGNUPS_ALLOWED=true
      - INVITATIONS_ALLOWED=ture
      - WEBSOCKET_ENABLED=false
      # 是否启用WEBSOCKET，true/false
      - ADMIN_TOKEN=【新建一个密码，注意不要泄露】
      # 管理员密钥
      - PUID=1000
      - PGID=100
      # 用户和用户组权限，ssh中使用“id 用户名”查看，用户组一般为100(users)
      # 第一个用户而言，群晖为1026，新绿联为1001，linux类系统为1000，后续用户均+1
      - UMASK=022
      # 默认创建新文件的权限，一般写022
      - TZ=Asia/Shanghai
      # 时区
    network_mode: bridge
    # 80端口被占用，不能用host
    ports:
      - 4743:80/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
