# 官方文档
# https://hub.docker.com/r/fallenbagel/jellyseerr
# https://github.com/Fallenbagel/jellyseerr

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    # 镜像地址
    container_name: jellyseerr
    # 容器名字
    hostname: jellyseerr
    # 主机名
    volumes:
      - /vol1/1000/docker/jellyseerr:/app/config
      # 配置文件目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 5055:5055/tcp
      # WebUI 端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3