# 官网
# https://www.photopea.com

# 编译教程
# https://post.smzdm.com/p/aovl8lo7
# https://zhuanlan.zhihu.com/p/684972393

# 网友编译现成dockre镜像，支持x86和arm64v8
# https://hub.docker.com/r/mysll/ps-offline
# https://github.com/mysll/ps-offline

---
version: "3"
# 最后编辑时间：2024-05-06
services:
  photopea:
    image: mysll/ps-offline:latest
    # 镜像地址
    container_name: photopea
    # 容器名字
    hostname: photopea
    # 主机名
    entrypoint: python3 -m http.server --directory www.photopea.com 8887
    # 8887为编译的端口号，可自定义
    network_mode: host
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3