# 官方文档
# https://hub.docker.com/r/ddsderek/easyimage
# https://github.com/ddsderek/easyimage

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  easyimage:
    image: ddsderek/easyimage:latest
    # 镜像地址
    container_name: easyimage
    # 容器名字
    hostname: easyimage
    # 主机名
    volumes:
      - /vol1/1000/docker/easyimage:/app/web/config
      # 配置文件目录
      - /vol1/1000/docker/简单图床:/app/web/i
      # 图床目录
    environment:
      - PUID=1000
      - PGID=100
      # 用户和用户组权限，ssh中使用“id 用户名”查看，用户组一般为100(users)
      # 第一个用户而言，群晖为1026，新绿联为1001，linux类系统为1000，后续用户均+1
      - TZ=Asia/Shanghai
      # 时区
    network_mode: bridge
    # 80端口被占用，不能用host
    ports:
      - 8280:80/tcp
      # WebUI 端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3