# 官方文档
# https://hub.docker.com/r/linuxserver/mariadb
# https://mariadb.com

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  mariadb:
    image: linuxserver/mariadb
    # 镜像地址
    container_name: mariadb
    # 容器名字
    hostname: mariadb
    # 主机名
    volumes:
      - 【这里替换为你的docker数据存放目录】/mariadb:/config
      # 配置目录
    environment:
      - MYSQL_ROOT_PASSWORD=【root账号的密码，切勿泄露】
      # mariadb管理者密码，账户为root
      # 不推荐其他容器都直接使用root管理者账号使用数据库，而是在数据库中创建子账号来访问子数据库
      - PUID=1000
      # 用户权限，群晖用户一般写1026，unraid用户写1000，视情况写0，即root
      - PGID=100
      # 用户组权限
      - UMASK=022
      # 默认创建新文件的权限，一般写022
      - TZ=Asia/Shanghai
      # 时区
      # - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql
      # 远程连接别的服务器上的数据库，需要就写
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 3306:3306/tcp
      # 非WebUI网页界面，直接调用即可
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      # 该镜像无WebUI网页界面，调用即可
      icon: http://IP:PORT/i/user_01/mariadb_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: /mnt/user/LOGO/mariadb.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑