# 官方文档
# https://dpanel.cc
# https://github.com/donknap/dpanel
# https://hub.docker.com/r/dpanel/dpanel

---
version: "3"
# 最后编辑时间：2024-11-28
services:
  dpanel:
    image: dpanel/dpanel:latest
    # 镜像地址，tag可选 latest/lite
    # lite 版去掉了域名转发相关，需要自行转发域名绑定容器，不需要绑定 80 及 443 端口
    container_name: dpanel
    # 容器名字
    hostname: dpanel
    # 主机名
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # docker核心
      - /share/Container/dpanel:/dpanel
      # 数据库文件目录
    network_mode: bridge
    # 推荐使用bridge模式，8080有别的要用
    ports:
      - 8807:8080/tcp
      # WebUI 端口
      - 11180:80/tcp
      - 11443:443/tcp
      # 域名转发相关，lite版不需要
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
