# 官方文档
# https://sillytavern.app
# https://docs.sillytavern.app/installation/docker
# https://github.com/SillyTavern/SillyTavern

# Linux 系统一键安装脚本
# https://github.com/mxw13579/silly-tavern-docker-starts

# 教程
# https://post.smzdm.com/p/amvwp7kv
# https://www.hqshi.cn/info/knowledge/sillytavern-guide

# 初次部署以后，会在 /config 文件夹内生成一份config.yaml，按照以下要求修改并保存，然后重启一次容器
# 第03行 改为 listen: true (必须)
# 第09行 改为 ipv6: ture (可选)
# 第12行 改为 port: 48000 (可选，华硕NAS推荐修改)
# 在18行后面按回车键，输入：- 172.17.0.* (必须，照抄即可，此为你的查看bridge网段的网关，如果你有使用macvlan/ipvlan，则额外添加，根据本人观察docker的bridge网关均为172.17.0.1)
# 第22、23行为账号密码，建议修改，默认为 user/password

---
version: "3"
# 最后编辑时间：2025-02-27
services:
  sillytavern:
    image: ghcr.io/sillytavern/sillytavern:latest
    # 镜像地址
    container_name: sillytavern
    # 容器名字
    hostname: sillytavern
    # 主机名
    volumes:
      - /share/Container/sillytavern/config:/home/node/app/config
      # 配置文件目录
      - /share/Container/sillytavern/data:/home/node/app/data
      # 用户数据目录data，插件目录plugins
      - /share/Container/sillytavern/plugins:/home/node/app/plugins
      # 官方插件目录
      - /share/Container/sillytavern/extensions:/home/node/app/public/scripts/extensions/third-party
      # 第三方插件目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 8000:8000/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
