# 官方文档
# https://hub.docker.com/r/privoce/vocechat-server

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  vocechat:
    image: privoce/vocechat-server:latest
    # 镜像地址
    container_name: vocechat
    # 容器名字
    hostname: vocechat
    # 主机名
    network_mode: bridge
    # 推荐使用bridge模式，3000有别的docker镜像要用
    ports:
      - 3040:3000/tcp 
      # WebUI http端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
