# 官方文档
# https://bitwarden.com
# https://hub.docker.com/r/vaultwarden/server
# 广域网中使用，需要https，建议使用lucky/npm进行反代

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  vaultwarden:
    image: vaultwarden/server:latest
    # 镜像地址
    container_name: vaultwarden
    # 容器名字
    hostname: vaultwarden
    # 主机名
    volumes:
      - /share/Container/vaultwarden:/data
      # 配置文件目录
    environment:
      - ADMIN_TOKEN=【管理者密钥，写复杂点增加安全性】
      # 管理者密钥，自定义一个密钥，访问 http://IP:PORT/admin 中使用
      - SIGNUPS_ALLOWED=true
      # 是否允许登录，默认为true
      - INVITATIONS_ALLOWED=true
      # 是否允许邀请，默认为true
      - WEBSOCKET_ENABLED=false
      # websocket启动，默认为false
      - TZ=Asia/Shanghai
      # 时区
    network_mode: bridge
    # 80端口被占用，不能用host
    ports:
      - 4743:80/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
