# 官方文档
# https://min.io
# https://hub.docker.com/r/minio/minio
# 部署教程
# https://zhuanlan.zhihu.com/p/684175456

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  minio:
    image: minio/minio:latest
    # 镜像地址
    container_name: minio
    # 容器名字
    hostname: minio
    # 主机名
    command: server /minio --console-address :9090
    # /minio为对象存储的目录
    # 9090为WebUI容器端口
    volumes:
      - /share/Container/MinIO:/data
      # 配置文件目录
      - /share/Public/MinIO:/minio
      # 对象存储的目录
    environment:
      - PUID=1000
      - PGID=100
      # 用户和用户组权限，ssh中使用“id 用户名”查看，用户组一般为100(users)
      # 第一个用户而言，群晖为1026，威联通为1000，新绿联为1001，linux类系统一般为1000，后续用户均+1
      - UMASK=022
      # 默认创建新文件的权限，一般写022
      - TZ=Asia/Shanghai
      # 时区
      - MINIO_ROOT_USER=这里写你的用户名字
      - MINIO_ROOT_PASSWORD=新建一个密码
      # MINIO的管理者账号和密码
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 9090:9090/tcp
      # WebUI 端口
      # - 9000:9000/tcp
      # api 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3