# 官方文档
# https://hub.docker.com/r/jgraph/drawio
# https://www.drawio.com
# 注意：drawio是在线编辑，文件并不会存储到nas端本地
# 如需在WebUI上编辑思维导图并保存到本地，建议安装部署webos或者kodbox，里面集成了

---
version: "3"
# 最后编辑时间：2024-04-20
services:
  drawio:
    image: jgraph/drawio:latest
    # 镜像地址
    container_name: drawio
    # 容器名字
    hostname: drawio
    # 主机名
    network_mode: bridge
    # 8080端口有别的docker容器用到，所以使用bridge
    ports:
      - 8282:8080/tcp
      # WebUI http端口
      - 8443:8443/tcp
      # WebUI https端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
