# 官方文档
# https://github.com/zhimin-dev/iptv-checker
# https://hub.docker.com/r/zhimin/iptvchecker

---
version: "3"
# 最后编辑时间：2024-05-06
services:
  iptv-checker:
    image: zmisgod/iptvchecker:latest
    # 镜像地址
    container_name: iptv-checker
    # 容器名字
    hostname: iptv-checker
    # 主机名
    volumes:
      - /volume1/docker/iptv-checker:/app/static/output
      # 输出文件目录
    environment:
      - WEB_PORT=8089
      # 自定义容器端口，默认为8089
    # network_mode: bridge
    network_mode: host
    # 推荐自定义容器端口，然后使用host模式，可以获取到iptv6源，如果不需要则忽略
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 8089:8089/tcp
      # WebUI 端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
