# 官方文档
# https://hub.docker.com/r/qdtoday/qd
# https://github.com/qd-today/qd

---
version: "3"
# 最后编辑时间：2024-06-26
services:
  qiandao:
    image: qdtoday/qd:latest
    # 镜像地址
    container_name: qiandao
    # 容器名字
    hostname: qiandao
    # 主机名
    volumes:
      - /volume1/docker/qiandao:/usr/src/app/config
      # 配置文件目录
    environment:
      - PUID=1000
      - PGID=100
      # 用户和用户组权限，ssh中使用“id 用户名”查看，用户组一般为100(users)
      # 第一个用户而言，群晖为1026，新绿联为1001，linux类系统为1000，后续用户均+1
      - TZ=Asia/Shanghai
      # 时区
    network_mode: bridge
    # 80端口被占用，不能用host
    ports:
      - 12345:80/tcp
      # WebUI 端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
