# 官方文档
# https://hub.docker.com/r/jeessy/ddns-go

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  ddns-go:
    image: jeessy/ddns-go:latest
    # 镜像地址
    container_name: ddns-go
    # 容器名字
    hostname: ddns-go
    # 主机名
    command: -l :9876 -f 300
      # 9876为WebUI端口，可自定义
      # 300为刷新解析间隔时间，可自定义
    volumes:
      - /volume1/docker/ddns-go:/root
      # 配置文件目录，文件是隐藏的，需要通过ssh进行访问，很重要，切勿泄露
    # network_mode: bridge
    network_mode: host
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3