# 官方文档
# https://www.aipan.me/blog/如何部署和aipan.me 同样的网站-5-1734676015648
# https://hub.docker.com/r/unilei/aipan-netdisk-search-simple
# 一键部署脚本
# curl -fsSL https://r2cf.aipan.me/deploy/quick-install.sh | sudo bash

# 这是去除所有的数据库的镜像，无需配置任何内容，即可使用，大多数用户对于数据库其实没有更多的需求.....

---
version: "3.9"
# 最后编辑时间：2025-01-05
services:
  aipan-netdisk-search-simple:
    image: unilei/aipan-netdisk-search-simple:latest
    # 镜像地址
    container_name: aipan-netdisk-search-simple
    # 容器名字
    hostname: aipan-netdisk-search-simple
    # 主机名
    network_mode: bridge
    # 3000有别的服务用到，因此使用bridge
    ports:
      - 3055:3000/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/aipan-netdisk-search_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3055]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/aipan-netdisk-search.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
